// Base
private _brief = ["Briefing",[[],[],[],["amf_uniform_03_CE_2",[]],[],[],"AMF_BERET_INFANTERIE","",["R3F_Monoculaire","","","",[],[],""],["ItemMap","","","","",""]]];
private _briefGenie = ["Briefing (génie)",[[],[],[],["amf_uniform_03_CE_2",[]],[],[],"AMF_BERET_GENIE","",["R3F_Monoculaire","","","",[],[],""],["ItemMap","","","","",""]]];
private _briefAlat = ["Briefing (ALAT)",[[],[],[],["amf_uniform_03_CE_2",[]],[],[],"AMF_BERET_ALAT_OR","",[],["ItemMap","","","","ACE_Altimeter",""]]];
private _briefFs = ["Briefing (FS)",[[],[],[],["amf_uniform_03_MTP_2",[]],[],[],"AMF_BERET_RPIMa","",[],["ItemMap","","","","ACE_Altimeter",""]]];

// Infanterie
private _infCds = ["[Infanterie] Chef de section",[["AMF_614_long_01_F","","AMF_LASER_PIRATE","AMF_Aimpoint_CompM5",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip3"],[],["AMF_Glock_17_TAN","","","",["16Rnd_9x21_Mag",17],[],""],["amf_uniform_01_CE_OD",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_smb_tl_grn",[["ACRE_PRC343",1],["ACRE_PRC152",1],["30Rnd_556x45_Stanag_red",7,30],["SmokeShell",4,1],["HandGrenade",2,1],["SmokeShellBlue",1,1],["ACE_Chemlight_IR",2,1],["SmokeShellRed",1,1],["SmokeShellGreen",1,1],["B_IR_Grenade",1,1],["16Rnd_9x21_Mag",1,17]]],[],"amf_felin_cover_CE_2","",["R3F_JIM_LR","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]]];
private _infRadio = ["[Infanterie] Opérateur radio",[["AMF_614_long_01_F","","AMF_LASER_PIRATE","AMF_Aimpoint_CompM5",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip3"],[],[],["amf_uniform_01_CE_OD",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_smb_tl_grn",[["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",4,1],["HandGrenade",2,1],["SmokeShellBlue",1,1],["Chemlight_red",4,1],["Chemlight_green",4,1],["Chemlight_blue",2,1]]],["R3F_sac_radio_TFR_Lourd_TAN",[["ACRE_PRC117F",1],["ACRE_PRC343",1],["B_IR_Grenade",2,1]]],"AMF_FELIN_COVER_TAN_EARPROT_OD_2","",["R3F_JIM_LR","","","",["Laserbatteries",1],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]]];

private _infCdg = ["[Infanterie] Chef de groupe",[["AMF_614_long_01_F","","AMF_LASER_PIRATE","AMF_Eotech_552",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip3"],[],["AMF_Glock_17_TAN","","","",["16Rnd_9x21_Mag",17],[],""],["amf_uniform_01_CE_OD",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_smb_tl_grn",[["ACRE_PRC343",1],["ACRE_PRC152",1],["30Rnd_556x45_Stanag_red",7,30],["SmokeShell",4,1],["HandGrenade",2,1],["SmokeShellBlue",1,1],["ACE_Chemlight_IR",2,1],["SmokeShellRed",1,1],["16Rnd_9x21_Mag",1,17],["SmokeShellGreen",1,1],["B_IR_Grenade",1,1]]],[],"amf_felin_cover_CE_2","rhs_googles_black",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide_Black"]]];
private _infCde300 = ["[Infanterie] Chef d'équipe 300",[["AMF_614_long_01_F","","AMF_LASER_PIRATE","AMF_Aimpoint_CompM5",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip3"],[],["AMF_Glock_17_TAN","","","",["16Rnd_9x21_Mag",17],[],""],["amf_uniform_01_CE_OD",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_smb_tl_grn",[["ACRE_PRC343",1],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",4,1],["HandGrenade",2,1],["SmokeShellBlue",1,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1],["16Rnd_9x21_Mag",1,17]]],[],"amf_felin_cover_CE_2","rhs_googles_black",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide_Black"]]];
private _infAt300 = ["[Infanterie] Fusilier AT 300",[["AMF_614_long_01_F","","AMF_LASER_PIRATE","R3F_comp_m5",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip3"],["rhs_weap_M136_hedp","","","",[],[],""],[],["amf_uniform_01_CE_OD",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_smb_inb_grn",[["ACRE_PRC343",1],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",4,1],["HandGrenade",2,1],["SmokeShellBlue",1,1],["Chemlight_red",4,1],["Chemlight_green",4,1],["Chemlight_blue",2,1]]],[],"amf_felin_cover_tan_2","",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide_Black"]]];
private _infCde600 = ["[Infanterie] Chef d'équipe 600",[["AMF_614_long_01_F","","AMF_LASER_PIRATE","AMF_Aimpoint_CompM5",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip3"],[],["AMF_Glock_17_TAN","","","",["16Rnd_9x21_Mag",17],[],""],["amf_uniform_01_CE_OD",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_smb_tl_grn",[["ACRE_PRC343",1],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",4,1],["HandGrenade",2,1],["SmokeShellBlue",1,1],["Chemlight_red",4,1],["Chemlight_green",4,1],["Chemlight_blue",2,1],["16Rnd_9x21_Mag",1,17]]],[],"amf_felin_cover_CE_2","rhs_googles_black",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide_Black"]]];
private _infMg600 = ["[Infanterie] Mitrailleur",[["rhs_weap_minimi_para_railed","","","R3F_J4",["rhsusf_200Rnd_556x45_box",200],[],"rhsusf_acc_saw_bipod"],[],[],["amf_uniform_01_CE_OD",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_smb_mc_grn",[["ACRE_PRC343",1],["rhsusf_100Rnd_556x45_soft_pouch",3,100]]],[],"AMF_FELIN_COVER_EARPROT_OD_2","",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide_Black"]]];
private _infGl600 = ["[Infanterie] Grenadier",[["rhs_weap_hk416d145_m320","","AMF_LASER_PIRATE","AMF_Eotech_552",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],["rhs_mag_M441_HE",1],""],[],[],["amf_uniform_01_CE_OD",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_smb_grb_grn",[["ACRE_PRC343",1],["SmokeShell",4,1],["HandGrenade",2,1],["SmokeShellBlue",1,1],["Chemlight_red",4,1],["Chemlight_green",4,1],["Chemlight_blue",2,1],["30Rnd_556x45_Stanag_red",8,30]]],["AMF_FELIN_BACKPACK",[["rhs_mag_M441_HE",11,1],["rhs_mag_M583A1_white",2,1],["rhs_mag_m713_Red",6,1],["rhs_mag_m714_White",8,1]]],"AMF_FELIN_MOUNT_EARPROT_OD_2","",["R3F_Monoculaire","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]]];

private _infTireurEryx = ["[Infanterie] Tireur ERYX",[["AMF_614_long_01_F","","AMF_LASER_PIRATE","R3F_comp_m5",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip2"],["R3F_ERYX","","","",[],[],""],[],["amf_uniform_01_CE_OD",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_smb_inb_grn",[["ACRE_PRC343",1],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",4,1],["HandGrenade",2,1],["SmokeShellBlue",1,1],["Chemlight_red",4,1],["Chemlight_green",4,1],["Chemlight_blue",2,1]]],[],"amf_felin_cover_CE_2","",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide_Black"]]];
private _infAssistEryx1 = ["[Infanterie] Aide ERYX",[["AMF_614_long_01_F","","AMF_LASER_PIRATE","AMF_Aimpoint_CompM5",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip3"],[],[],["amf_uniform_01_CE_OD",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_IR_Strobe_Item",1]]],["amf_smb_inb_grn",[["ACRE_PRC343",1],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",4,1],["HandGrenade",2,1],["SmokeShellBlue",1,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_HiGreen",4,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_IR",2,1]]],["AMF_FELIN_BACKPACK",[["R3F_ERYX_mag",2,1]]],"amf_felin_cover_CE_2","rhs_googles_black",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]]];

private _infGenie = ["[Infanterie] Génie",[["AMF_614_short_01_F","","","AMF_Aimpoint_CompM5",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip3"],[],[],["amf_uniform_01_CE_OD",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_smb_me_grn",[["ACRE_PRC343",1],["SmokeShell",4,1],["HandGrenade",2,1],["SmokeShellBlue",1,1],["Chemlight_red",4,1],["Chemlight_green",4,1],["Chemlight_blue",2,1],["30Rnd_556x45_Stanag_red",8,30]]],["AMF_FELIN_BACKPACK",[["ACE_EntrenchingTool",1],["ACE_wirecutter",1],["ACE_DefusalKit",1],["ACE_Clacker",1],["ACE_SpraypaintBlue",1],["ACE_SpraypaintGreen",1],["rhsusf_m112x4_mag",2,1],["rhsusf_m112_mag",2,1],["ToolKit",1]]],"amf_felin_cover_CE_2","rhs_googles_black",["R3F_Monoculaire","","","",[],[],""],["ItemMap","","","ItemCompass","","ACE_NVG_Wide"]]];
private _infGenieEOD = ["[Infanterie] EOD",[["AMF_614_short_01_F","","AMF_LASER_PIRATE","AMF_Eotech_552",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip3"],[],["hgun_esd_01_F","muzzle_antenna_02_f","acc_esd_01_flashlight","",[],[],""],["amf_uniform_01_CE_OD",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_smb_me_grn",[["ACRE_PRC343",1],["SmokeShell",4,1],["HandGrenade",2,1],["SmokeShellBlue",1,1],["Chemlight_red",4,1],["Chemlight_green",4,1],["Chemlight_blue",2,1],["30Rnd_556x45_Stanag_red",6,30]]],["AMF_FELIN_BACKPACK",[["MineDetector",1],["ACE_Clacker",1],["ACE_SpraypaintGreen",1],["muzzle_antenna_01_f",1],["muzzle_antenna_03_f",1],["ACE_EntrenchingTool",1],["ToolKit",1],["ACE_wirecutter",1],["ACE_SpraypaintBlue",1],["ACE_DefusalKit",1],["rhsusf_m112_mag",4,1],["SatchelCharge_Remote_Mag",1,1]]],"amf_felin_cover_CE_2","",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","","ACE_NVG_Wide"]]];

private _infMedic = ["[Infanterie] Médecin",[["AMF_614_short_01_F","","AMF_LASER_PIRATE","AMF_Eotech_552",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip3"],[],[],["amf_uniform_01_CE_OD",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_smb_me_grn",[["ACRE_PRC343",1],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",4,1],["HandGrenade",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_HiGreen",4,1],["ACE_Chemlight_HiBlue",2,1]]],["AMF_FELIN_BACKPACK_MEDIC",[["ACE_splint",10],["ACE_epinephrine",10],["ACE_morphine",10],["ACE_packingBandage",10],["ACE_elasticBandage",10],["ACE_tourniquet",8],["ACE_quikclot",10],["ACE_salineIV",6],["ACE_salineIV_250",6],["ACE_salineIV_500",6],["ACE_surgicalKit",1]]],"amf_felin_cover_tan_2","",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide_Black"]]];

private _infTp417 = ["[Infanterie] Tireur de précision (HK417)",[["AMF_714_short_01_F","","","rhsusf_acc_premier_low",["20Rnd_762x51_HK417_mag",20],[],"bipod_01_F_blk"],[],["AMF_Glock_17_TAN","","","",["16Rnd_9x21_Mag",17],[],""],["amf_uniform_01_CE_OD",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_smb_tp_hk417_grn",[["ACRE_PRC343",1],["20Rnd_762x51_HK417_mag",8,20],["SmokeShell",4,1],["HandGrenade",2,1],["ACE_Chemlight_HiGreen",4,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiBlue",2,1],["16Rnd_9x21_Mag",1,17]]],[],"amf_felin_cover_CE_2","",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide_Black"]]];

private _infFusilier = ["[Infanterie] Fantassin",[["AMF_614_long_01_F","","AMF_LASER_PIRATE","R3F_comp_m5",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip3"],[],[],["amf_uniform_01_CE_OD",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_smb_inb_grn",[["ACRE_PRC343",1],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",4,1],["HandGrenade",2,1],["SmokeShellBlue",1,1],["Chemlight_red",4,1],["Chemlight_green",4,1],["Chemlight_blue",2,1]]],[],"amf_felin_cover_CE_2","rhs_googles_black",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide_Black"]]];

private _infJtac = ["[Infanterie] JTAC",[["AMF_614_short_01_F","","AMF_LASER_PIRATE","AMF_Eotech_552",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip3"],[],[],["amf_uniform_01_CE_OD",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_smb_me_grn",[["30Rnd_556x45_Stanag_red",8,30],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShellBlue",3,1],["SmokeShellRed",3,1],["SmokeShellGreen",3,1],["HandGrenade",1,1],["SmokeShell",2,1]]],["R3F_sac_radio_TFR_Lourd_TAN",[["ACE_microDAGR",1],["ACRE_PRC117F",1],["ACRE_PRC343",1],["Laserbatteries",1,1],["B_IR_Grenade",2,1]]],"AMF_FELIN_COVER_TAN_EARPROT_OD_2","rhs_googles_black",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]]];
private _infNrbc = ["[Infanterie] Opérateur NRBC", [["AMF_614_long_01_F","","AMF_LASER_PIRATE","R3F_comp_m5",["30Rnd_556x45_Stanag_red",30],[],"amf_acc_614_grip3"],[],[],["U_I_E_CBRN_Suit_01_EAF_F",[["ACE_splint",4],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1]]],["amf_smb_me_grn",[["30Rnd_556x45_Stanag_red",8,30],["HandGrenade",2,1],["SmokeShell",4,1],["SmokeShellBlue",1,1],["SmokeShellGreen",1,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_IR",1,1]]],["AMF_FELIN_BACKPACK",[]],"amf_felin_cover_tan_2","G_AirPurifyingRespirator_01_F",[],["ItemMap","","ItemRadioAcreFlagged","ItemCompass","ACE_Altimeter","ACE_NVG_Wide_Black"]]];

// Blindé
private _blindeCdc = ["[Blindé] Chef de char",[["AMF_614_short_01_F","","","R3F_comp_m5",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip3"],[],[],["amf_uniform_01_CE_OD",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_smb_me_grn",[["ACRE_PRC343",1],["ACRE_PRC152",1],["30Rnd_556x45_Stanag_red",7,30],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_HiGreen",4,1],["HandGrenade",2,1],["SmokeShell",4,1]]],[],"H_HelmetCrew_B","",["R3F_Monoculaire","","","",[],[],""],["ItemMap","","","","",""]]];
private _blindeTireur = ["[Blindé] Tireur",[["AMF_614_short_01_F","","","R3F_comp_m5",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip3"],[],[],["amf_uniform_01_CE_OD",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_smb_me_grn",[["ACRE_PRC343",1],["ACRE_PRC152",1],["30Rnd_556x45_Stanag_red",7,30],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_HiGreen",4,1],["HandGrenade",2,1],["SmokeShell",4,1]]],[],"H_HelmetCrew_B","",["R3F_Monoculaire","","","",[],[],""],["ItemMap","","","","",""]]];
private _blindePilote = ["[Blindé] Pilote",[["AMF_614_short_01_F","","","R3F_comp_m5",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip3"],[],[],["amf_uniform_01_CE_OD",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_smb_me_grn",[["ACRE_PRC343",1],["ACRE_PRC152",1],["30Rnd_556x45_Stanag_red",7,30],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiRed",4,1],["ACE_Chemlight_HiGreen",4,1],["HandGrenade",2,1],["SmokeShell",4,1]]],[],"H_HelmetCrew_B","",["R3F_Monoculaire","","","",[],[],""],["ItemMap","","","","",""]]];

// FS
private _fsOperateur = ["[Force spéciale] Opérateur",[["AMF_614_short_FS_BLK","AMF_ROTEX_V","rhsusf_acc_anpeq15side_bk","rhsusf_acc_g33_T1",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip5"],[],["AMF_Glock_17_TAN","","acc_flashlight_pistol","",["16Rnd_9x21_Mag",17],[],""],["amf_uniform_05_MTP",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_DCS_05_TAN",[["ACRE_PRC148",1],["ACE_CTS9",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiBlue",2,1],["HandGrenade",2,1],["SmokeShell",4,1],["30Rnd_556x45_Stanag_red",7,30],["16Rnd_9x21_Mag",2,17]]],[],"AMF_OPSCORE_GREY2","amf_balaclava_ranger",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]]];
private _fsCdg = ["[Force spéciale] Chef de groupe",[["AMF_614_long_FS_TAN","AMF_ROTEX_V","rhsusf_acc_anpeq15side","rhsusf_acc_su230_c",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip7"],[],["AMF_Glock_17_TAN","","acc_flashlight_pistol","",["16Rnd_9x21_Mag",17],[],""],["amf_uniform_05_MTP",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_DCS_05_TAN",[["ACRE_PRC148",1],["ACE_CTS9",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiBlue",2,1],["HandGrenade",2,1],["SmokeShell",4,1],["30Rnd_556x45_Stanag_red",7,30],["16Rnd_9x21_Mag",1,17]]],["AMF_rush24_01_TAN",[["ACRE_VHF30108",1],["ACRE_PRC117F",1],["ACE_IR_Strobe_Item",2],["B_IR_Grenade",1,1]]],"AMF_OPSCORE_GREY2","amf_balaclava_ranger",["R3F_JIM_LR","","","",["Laserbatteries",1],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]]];
private _fsMed = ["[Force spéciale] Médecin",[["AMF_614_short_fs2_tan","AMF_ROTEX_V","rhsusf_acc_anpeq15side","rhsusf_acc_EOTECH",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip7"],[],["AMF_Glock_17_TAN","","acc_flashlight_pistol","",["16Rnd_9x21_Mag",17],[],""],["amf_uniform_05_MTP",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_DCS_05_TAN",[["ACRE_PRC148",1],["30Rnd_556x45_Stanag_red",8,30],["ACE_CTS9",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiBlue",2,1],["HandGrenade",2,1],["SmokeShell",4,1],["16Rnd_9x21_Mag",1,17]]],["AMF_rush24_01_TAN",[["ACE_splint",6],["ACE_epinephrine",10],["ACE_morphine",10],["ACE_packingBandage",10],["ACE_elasticBandage",10],["ACE_tourniquet",6],["ACE_quikclot",10],["ACE_salineIV",6],["ACE_salineIV_250",6],["ACE_salineIV_500",6],["ACE_surgicalKit",1]]],"AMF_OPSCORE_GREY2","amf_balaclava_ranger",["R3F_JIM_LR","","","",["Laserbatteries",1],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]]];
private _fsMitrailleur = ["[Force spéciale] Mitrailleur",[["rhs_weap_m249_pip_S","","","rhsusf_acc_su230",["rhsusf_200rnd_556x45_mixed_box",200],[],"rhsusf_acc_grip1"],[],["AMF_Glock_17_TAN","","acc_flashlight_pistol","",["16Rnd_9x21_Mag",17],[],""],["amf_uniform_05_MTP",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_DCS_03_TAN",[["ACRE_PRC148",1],["rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",3,100],["16Rnd_9x21_Mag",2,17]]],["AMF_rush24_01_TAN",[["ACE_CTS9",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiBlue",2,1],["HandGrenade",2,1],["SmokeShell",4,1]]],"AMF_OPSCORE_GREY2","amf_balaclava_ranger",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]]];
private _fsTp = ["[Force spéciale] Tireur de précision",[["R3F_HK417M_HG_DES","R3F_SILENCIEUX_HK417_DES","","optic_KHS_tan",["R3F_20Rnd_762x51_HK417",20],[],"R3F_BIPIED_HK417_DES"],[],["AMF_Glock_17_TAN","","acc_flashlight_pistol","",["16Rnd_9x21_Mag",17],[],""],["amf_uniform_05_MTP",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_RangeCard",1]]],["amf_DCS_03_TAN",[["ACRE_PRC148",1],["ACE_Kestrel4500",1],["ACE_IR_Strobe_Item",1],["16Rnd_9x21_Mag",1,17],["R3F_20Rnd_762x51_HK417",8,20],["ACE_Chemlight_IR",2,1],["HandGrenade",2,1],["SmokeShell",3,1],["SmokeShellBlue",1,1]]],["AMF_rush24_01_TAN",[["ACE_CTS9",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiBlue",2,1],["HandGrenade",2,1],["SmokeShell",4,1]]],"AMF_OPSCORE_GREY2","amf_balaclava_od",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]]];
private _fsBreacher = ["[Force spéciale] Breacher",[["AMF_614_short_FS_TAN","AMF_ROTEX_V","rhsusf_acc_anpeq15side","rhsusf_acc_g33_xps3",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip6"],[],["AMF_Glock_17_TAN","","acc_flashlight_pistol","",["16Rnd_9x21_Mag",17],[],""],["amf_uniform_05_MTP",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_DCS_02_TAN",[["ACRE_PRC148",1],["ACE_CTS9",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiBlue",2,1],["HandGrenade",2,1],["SmokeShell",4,1],["30Rnd_556x45_Stanag_red",8,30],["16Rnd_9x21_Mag",1,17]]],["AMF_rush24_01_TAN",[["R3F_LAMPE_SURB",1],["R3F_7Rnd_M4S90",6,7],[["R3F_M4S90","","","",[],[],""],1]]],"AMF_OPSCORE_GREY2","amf_balaclava_od",["R3F_JIM_LR","","","",["Laserbatteries",1],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]]];
private _fsNrbc = ["[Force spéciale] Opérateur NRBC",[["AMF_614_short_FS4_BLK","AMF_ROTEX_V","ACE_acc_pointer_green","AMF_AIMPOINT_MICRO_T2",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip5"],[],["AMF_Glock_17_TAN","","acc_flashlight_pistol","",["16Rnd_9x21_Mag",17],[],""],["U_B_CBRN_Suit_01_MTP_F",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_plate_ca3_green",[["ACRE_PRC148",1],["ACE_CTS9",2,1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiBlue",2,1],["HandGrenade",2,1],["SmokeShell",4,1],["30Rnd_556x45_Stanag_red",8,30],["16Rnd_9x21_Mag",1,17]]],[],"AMF_TC801_GRN","G_AirPurifyingRespirator_01_F",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide_Black"]]];
private _fsJtac = ["[Force spéciale] JTAC",[["AMF_614_short_FS_BLK","AMF_ROTEX_V","rhsusf_acc_anpeq15side","rhsusf_acc_g33_xps3",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip5"],[],["AMF_Glock_17_TAN","","acc_flashlight_pistol","",["16Rnd_9x21_Mag",17],[],""],["amf_uniform_05_MTP",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_MapTools",1],["ACE_microDAGR",1]]],["amf_DCS_01_TAN",[["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiBlue",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShellBlue",2,1],["SmokeShellGreen",4,1],["SmokeShellRed",4,1],["HandGrenade",1,1],["SmokeShell",2,1],["16Rnd_9x21_Mag",1,17],["30Rnd_556x45_Stanag_red",7,30]]],["R3F_sac_radio_TFR_Lourd_TAN",[["ACRE_PRC117F",1],["ACRE_PRC148",1],["Laserbatteries",1,1],["30Rnd_556x45_Stanag",1,30],["B_IR_Grenade",2,1]]],"AMF_OPSCORE_TAN2_2","amf_balaclava_ranger",["R3F_JIM_LR","","","",["Laserbatteries",1],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]]];

private _fsTeBarrett = ["[Force spéciale] Tireur d'élite (Barrett)",[["rhs_weap_M107_w","","","rhsusf_acc_M8541",["rhsusf_mag_10Rnd_STD_50BMG_M33",10],[],""],[],["rhsusf_weap_glock17g4","rhsusf_acc_omega9k","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["R3F_uniform_Ghillie",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",2]]],["amf_DCS_03_OD",[["ACRE_PRC148",1],["ACE_IR_Strobe_Item",4],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_Chemlight_IR",4,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShell",4,1],["HandGrenade",2,1],["rhsusf_mag_10Rnd_STD_50BMG_M33",1,10],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["B_Kitbag_mcamo",[["ACE_Tripod",1],["rhsusf_mag_10Rnd_STD_50BMG_mk211",3,10],["rhsusf_mag_10Rnd_STD_50BMG_M33",2,10]]],"AMF_OPSCORE2_BLACK","",["R3F_JIM_LR","","","",["Laserbatteries",1],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]]];
private _fsTeSpotter = ["[Force spéciale] Observateur (HK417)",[["AMF_714_Long_01_F","muzzle_snds_M","","rhsusf_acc_M8541_mrds",["20Rnd_762x51_HK417_mag",20],[],"bipod_01_F_blk"],[],["AMF_Glock_17","muzzle_snds_L","acc_flashlight_pistol","",["16Rnd_9x21_Mag",17],[],""],["R3F_uniform_Ghillie",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",2]]],["amf_DCS_03_OD",[["ACRE_PRC148",1],["ACE_microDAGR",1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShell",4,1],["HandGrenade",2,1],["20Rnd_762x51_HK417_mag",7,20],["ACE_Chemlight_IR",4,1],["16Rnd_9x21_Mag",2,17]]],["B_AssaultPack_khk",[["ACE_IR_Strobe_Item",4],["ACE_Kestrel4500",1],["ACE_Tripod",1],["ACE_RangeCard",1]]],"AMF_OPSCORE2_BLACK","",["R3F_JIM_LR","","","",["Laserbatteries",1],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]]];

private _fsPlongeurDemo = ["[Force spéciale] Plongeur démolisseur",[["amf_hk_mp5_01_f","muzzle_snds_L","","",["30Rnd_9x19_mag",30],[],""],[],["rhsusf_weap_glock17g4","rhsusf_acc_omega9k","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["U_O_Wetsuit",[["ACE_splint",1],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_Flashlight_MX991",1],["ACE_tourniquet",1],["ACRE_PRC148",1],["ACE_Chemlight_IR",2,1],["ACE_Chemlight_HiRed",2,1],["ACE_Chemlight_HiGreen",2,1],["SmokeShell",2,1],["rhsusf_mag_17Rnd_9x19_FMJ",1,17],["20Rnd_556x45_UW_mag",4,20]]],["V_RebreatherB",[]],["rhs_tortila_black",[["ACE_Clacker",1],["ACE_DefusalKit",1],["30Rnd_9x19_mag",4,30],["SatchelCharge_Remote_Mag",1,1],["rhsusf_m112_mag",2,1],[["arifle_SDAR_F","","","",[],[],""],1],["amf_DCS_01_BLK",false]]],"AMF_OPSCORE2_BLACK","G_B_Diving",[],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide"]]];

private _fsEod = ["[Force spéciale] EOD", [["AMF_614_short_FS_TAN","AMF_ROTEX_V","rhsusf_acc_anpeq15side","rhsusf_acc_g33_xps3",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip7"],[],["AMF_Glock_17_TAN","","acc_flashlight_pistol","",["16Rnd_9x21_Mag",17],[],""],["amf_uniform_05_MTP",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_CableTie",1]]],["amf_DCS_04_TAN",[["ACE_IR_Strobe_Item",1],["30Rnd_556x45_Stanag_red",8,30],["rhs_mag_an_m8hc",4,1],["ACE_CTS9",2,1],["rhs_mag_m67",2,1],["ACE_Chemlight_IR",2,1]]],["B_Kitbag_cbr",[["ACE_DefusalKit",1],["ACE_Clacker",1],["MineDetector",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["SatchelCharge_Remote_Mag",2,1],["DemoCharge_Remote_Mag",2,1]]],"AMF_OPSCORE_GREY2","amf_balaclava_ranger",["Binocular","","","",[],[],""],["ItemMap","","ItemRadioAcreFlagged","ItemCompass","ACE_Altimeter","ACE_NVG_Wide_Black"]]];

// ALAT
private _alatPilote = ["[ALAT] Pilote",[["amf_hk_mp5_01_f","","","",["30Rnd_9x19_mag",30],[],""],[],["AMF_Glock_17_TAN","","","",["16Rnd_9x21_Mag",17],[],""],["amf_uniform_03_CE_2",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_smb_me",[["ACRE_PRC148",1],["ACE_Flashlight_MX991",1],["30Rnd_9x19_mag",6,30],["16Rnd_9x21_Mag",2,17]]],[],"AMF_ALPHA900","",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","ACE_NVG_Wide_Black"]]];
private _alatTireur = ["[ALAT] Tireur mécanicien",[["AMF_614_short_01_F","","","AMF_Eotech_552",["30Rnd_556x45_Stanag",30],[],"amf_acc_614_grip2"],[],["AMF_Glock_17_TAN","","","",["16Rnd_9x21_Mag",17],[],""],["amf_uniform_01_CE_2",[["ACE_splint",2],["ACE_epinephrine",4],["ACE_morphine",4],["ACE_packingBandage",6],["ACE_elasticBandage",6],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1]]],["amf_plate_ca3_green",[["ACRE_PRC148",1],["ACE_Flashlight_MX991",1],["16Rnd_9x21_Mag",2,17],["30Rnd_556x45_Stanag_red",4,30]]],[],"AMF_ALPHA900_02","",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];


{
	_x params ["_name", "_loadout"];
	[_name, _loadout] call ace_arsenal_fnc_addDefaultLoadout;
} forEach [
	_brief,
	_briefGenie,
	_briefAlat,
	_briefFs,
	_infCds,
	_infRadio,
	_infCdg,
	_infCde300,
	_infAt300,
	_infCde600,
	_infMg600,
	_infGl600,
	_infTireurEryx,
	_infAssistEryx1,
	_infGenie,
	_infGenieEOD,
	_infMedic,
	_infTp417,
	_infFusilier,
	_infJtac,
	_infNrbc,
	_blindeCdc,
	_blindeTireur,
	_blindePilote,
	_fsOperateur,
	_fsCdg,
	_fsMed,
	_fsMitrailleur,
	_fsTp,
	_fsBreacher,
	_fsNrbc,
	_fsJtac,
	_fsTeBarrett,
	_fsTeSpotter,
	_fsPlongeurDemo,
	_fsEod,
	_alatPilote,
	_alatTireur
];