// Base
private _brief = ["Briefing", [[],[],[],["UK3CB_BAF_U_RolledUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],[],[],"UK3CB_BAF_H_Beret_PR","",[],["ItemMap","","","ItemCompass","ItemWatch",""]]];
private _briefTank = ["Briefing Royal Tanks", [[],[],[],["UK3CB_BAF_U_RolledUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],[],[],"UK3CB_BAF_H_Beret_RTR","",[],["ItemMap","","","ItemCompass","ItemWatch",""]]];
private _briefingRaf = ["Briefing RAF", [[],[],[],["UK3CB_BAF_U_HeliPilotCoveralls_RAF",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],[],[],"UK3CB_BAF_H_Beret_RAF","G_Aviator",[],["ItemMap","","","ItemCompass","ACE_Altimeter",""]]];
private _birefingSas = ["Briefing SAS", [[],[],[],["rhs_uniform_g3_blk",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],[],[],"UK3CB_BAF_H_Beret_SAS","UK3CB_BAF_G_Tactical_Grey",[],["ItemMap","","","ItemCompass","ItemWatch",""]]];

// Infanterie
private _infCds = ["[Infanterie] Chef de section", [["UK3CB_BAF_L85A3","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","UK3CB_BAF_TA31F_Hornbill",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_g"],[],["UK3CB_BAF_L117A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_IR_Strobe_Item",1]]],["UK3CB_BAF_V_Osprey_SL_D",[["ACE_IR_Strobe_Item",1],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",2,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1],["UK3CB_BAF_9_15Rnd",2,15],["UK3CB_BAF_SmokeShellRed",2,1],["UK3CB_BAF_556_30Rnd",10,30],["B_IR_Grenade",2,1]]],["UK3CB_BAF_B_Bergen_MTP_Radio_L_A",[["ACRE_PRC148",1],["ACRE_PRC117F",1],["ACRE_PRC343",1]]],"UK3CB_BAF_H_Mk7_Scrim_C","UK3CB_BAF_G_Tactical_Grey",["UK3CB_BAF_Soflam_Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","UK3CB_BAF_HMNVS"]]];
private _infJtac = ["[Infanterie] FAC", [["UK3CB_BAF_L85A3","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_LDS",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_g"],[],[],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["UK3CB_BAF_V_Osprey_Rifleman_F",[["ACE_IR_Strobe_Item",1],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellRed",3,1],["UK3CB_BAF_SmokeShellBlue",3,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1],["UK3CB_BAF_556_30Rnd",10,30],["B_IR_Grenade",2,1],["UK3CB_BAF_SmokeShellGreen",1,1]]],["UK3CB_BAF_B_Bergen_MTP_JTAC_H_A",[["ACRE_PRC117F",1],["ACRE_PRC343",1]]],"UK3CB_BAF_H_Mk7_Scrim_B","UK3CB_BAF_G_Tactical_Grey",["UK3CB_BAF_Soflam_Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","B_UavTerminal","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infRadio = ["[Infanterie] Opérateur radio", [["UK3CB_BAF_L85A2_RIS_G","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","UK3CB_BAF_TA31F_Hornbill",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_g"],[],[],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["UK3CB_BAF_V_Osprey_Rifleman_E",[["ACE_IR_Strobe_Item",1],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",2,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1],["UK3CB_BAF_556_30Rnd",10,30],["UK3CB_BAF_SmokeShellRed",2,1],["B_IR_Grenade",1,1]]],["UK3CB_BAF_B_Bergen_MTP_Radio_L_B",[["ACRE_PRC117F",1],["ACRE_PRC343",1]]],"UK3CB_BAF_H_Mk7_Scrim_C","UK3CB_BAF_G_Tactical_Grey",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infMedic = ["[Infanterie] Médecin", [["UK3CB_BAF_L85A2_RIS","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_LDS",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_g"],[],[],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["UK3CB_BAF_V_Osprey_Medic_C",[["ACRE_PRC343",1],["ACE_IR_Strobe_Item",1],["UK3CB_BAF_556_30Rnd",6,30],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",2,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1]]],["UK3CB_BAF_B_Bergen_MTP_Medic_H_B",[["ACE_splint",8],["ACE_epinephrine",10],["ACE_morphine",10],["ACE_packingBandage",20],["ACE_elasticBandage",20],["ACE_tourniquet",4],["ACE_salineIV",8],["ACE_salineIV_250",10],["ACE_salineIV_500",10],["ACE_surgicalKit",1],["ACE_EntrenchingTool",1]]],"UK3CB_BAF_H_Mk7_Camo_D","UK3CB_BAF_G_Tactical_Grey",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infGenieEOD = ["[Infanterie] EOD", [["UK3CB_BAF_L85A2_RIS_G","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_LDS",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_g"],[],["ACE_VMM3","","","",[],[],""],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["UK3CB_BAF_V_Osprey_Rifleman_E",[["ACRE_PRC343",1],["ACE_IR_Strobe_Item",1],["UK3CB_BAF_SmokeShell",4,1],["HandGrenade",2,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellBlue",1,1],["UK3CB_BAF_556_30Rnd",8,30],["ACE_Chemlight_IR",1,1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiRed",2,1]]],["UK3CB_BAF_B_Bergen_MTP_Sapper_L_A",[["ACE_Clacker",1],["ACE_DefusalKit",1],["ACE_SpraypaintRed",1],["ACE_SpraypaintGreen",1],["ACE_EntrenchingTool",1],["ToolKit",1],["DemoCharge_Remote_Mag",2,1]]],"UK3CB_BAF_H_Mk7_Camo_D","UK3CB_BAF_G_Tactical_Grey",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infRifleman = ["[Infanterie] Fusilier", [["UK3CB_BAF_L85A2_RIS_G","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","UK3CB_BAF_TA31F_Hornbill",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_g"],[],[],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["UK3CB_BAF_V_Osprey_Rifleman_F",[["ACRE_PRC343",1],["ACE_IR_Strobe_Item",1],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",2,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1],["UK3CB_BAF_556_30Rnd",10,30],["UK3CB_BAF_SmokeShellRed",2,1]]],[],"UK3CB_BAF_H_Mk7_Scrim_A","UK3CB_BAF_G_Tactical_Grey",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infTlAssault = ["[Infanterie] Chef d'équipe assaut", [["UK3CB_BAF_L85A3","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","UK3CB_BAF_TA31F_Hornbill",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_g"],[],["UK3CB_BAF_L117A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_IR_Strobe_Item",1]]],["UK3CB_BAF_V_Osprey_SL_D",[["ACRE_PRC343",1],["ACRE_PRC148",1],["ACE_IR_Strobe_Item",1],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",2,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1],["UK3CB_BAF_SmokeShellRed",2,1],["UK3CB_BAF_9_15Rnd",2,15],["UK3CB_BAF_556_30Rnd",10,30]]],[],"UK3CB_BAF_H_Mk7_Camo_D","UK3CB_BAF_G_Tactical_Grey",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infGl = ["[Infanterie] Grenadier", [["UK3CB_BAF_L85A3_UGL","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_LDS",["UK3CB_BAF_556_30Rnd",30],["UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",1],""],[],[],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["UK3CB_BAF_V_Osprey_Grenadier_B",[["ACRE_PRC343",1],["ACE_IR_Strobe_Item",1],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_556_30Rnd",10,30]]],["UK3CB_BAF_B_Bergen_MTP_Rifleman_L_B",[["UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",14,1],["UK3CB_BAF_1Rnd_SmokeRed_Grenade_shell",6,1],["UK3CB_BAF_1Rnd_Smoke_Grenade_shell",6,1],["UK3CB_BAF_UGL_FlareCIR_F",2,1]]],"UK3CB_BAF_H_Mk7_Scrim_A","UK3CB_BAF_G_Tactical_Grey",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infHeavyMg = ["[Infanterie] Mitrailleur lourd", [["UK3CB_BAF_L7A2","","","",["UK3CB_BAF_762_100Rnd",100],[],""],[],["UK3CB_BAF_L117A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["UK3CB_BAF_V_Osprey_MG_B",[["ACRE_PRC343",1],["ACE_IR_Strobe_Item",1],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_9_15Rnd",2,15],["UK3CB_BAF_762_100Rnd",3,100]]],[],"UK3CB_BAF_H_Mk7_Scrim_B","UK3CB_BAF_G_Tactical_Grey",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infMg = ["[Infanterie] Mitrailleur", [["UK3CB_BAF_L110A2RIS","","UK3CB_BAF_LLM_IR_Tan","UK3CB_BAF_TA31F",["UK3CB_BAF_556_200Rnd",200],[],""],[],["UK3CB_BAF_L117A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["UK3CB_BAF_V_Osprey_MG_B",[["ACRE_PRC343",1],["ACE_IR_Strobe_Item",1],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_556_100Rnd",4,100],["UK3CB_BAF_9_15Rnd",1,15]]],[],"UK3CB_BAF_H_Mk7_Net_B","UK3CB_BAF_G_Tactical_Grey",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infTlSupport = ["[Infanterie] Chef d'équipe soutiens", [["UK3CB_BAF_L85A3","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","UK3CB_BAF_TA31F_Hornbill",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_g"],[],["UK3CB_BAF_L117A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_IR_Strobe_Item",1]]],["UK3CB_BAF_V_Osprey_SL_D",[["ACRE_PRC343",1],["ACRE_PRC148",1],["ACE_IR_Strobe_Item",1],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",2,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1],["UK3CB_BAF_SmokeShellRed",2,1],["UK3CB_BAF_9_15Rnd",2,15],["UK3CB_BAF_556_30Rnd",10,30]]],[],"UK3CB_BAF_H_Mk7_Camo_D","UK3CB_BAF_G_Tactical_Grey",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infMarksman = ["[Infanterie] Marksman", [["UK3CB_BAF_L129A1","","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_PMII_312",["UK3CB_BAF_762_L42A1_20Rnd",20],[],"UK3CB_underbarrel_acc_fgrip_bipod"],[],["UK3CB_BAF_L117A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_IR_Strobe_Item",2]]],["UK3CB_BAF_V_Osprey_Marksman_A",[["ACRE_PRC343",1],["ACE_IR_Strobe_Item",1],["UK3CB_BAF_SmokeShell",3,1],["UK3CB_BAF_SmokeShellBlue",1,1],["UK3CB_BAF_SmokeShellRed",1,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1],["UK3CB_BAF_762_L42A1_20Rnd",7,20],["UK3CB_BAF_9_15Rnd",2,15]]],["UK3CB_BAF_B_Bergen_MTP_Rifleman_L_B",[["UK3CB_BAF_MaxiKite",1],["ACE_Kestrel4500",1],["ACE_EntrenchingTool",1],["ACE_RangeCard",1]]],"UK3CB_BAF_H_Mk7_Scrim_A","",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","","","ItemCompass","ItemWatch","UK3CB_BAF_HMNVS"]]];
private _infAt = ["[Infanterie] Fusilier AT", [["UK3CB_BAF_L85A2_RIS_G","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","UK3CB_BAF_TA31F_Hornbill",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_g"],["UK3CB_BAF_AT4_CS_AP_Launcher","","","",[],[],""],[],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["UK3CB_BAF_V_Osprey_Rifleman_F",[["ACRE_PRC343",1],["ACE_IR_Strobe_Item",1],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",2,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1],["UK3CB_BAF_556_30Rnd",10,30],["UK3CB_BAF_SmokeShellRed",2,1]]],[],"UK3CB_BAF_H_Mk7_Net_B","UK3CB_BAF_G_Tactical_Grey",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infAa = ["[Infanterie] Fusilier AA", [["UK3CB_BAF_L85A2_RIS_G","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","UK3CB_BAF_TA31F_Hornbill",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_g"],["rhs_weap_fim92","","","",["rhs_fim92_mag",1],[],""],[],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["UK3CB_BAF_V_Osprey_Rifleman_F",[["ACRE_PRC343",1],["ACE_IR_Strobe_Item",1],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",2,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1],["UK3CB_BAF_556_30Rnd",10,30],["UK3CB_BAF_SmokeShellRed",2,1]]],[],"UK3CB_BAF_H_Mk7_Net_B","UK3CB_BAF_G_Tactical_Grey",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infHeavyAt = ["[Infanterie] Spécialiste AT", [["UK3CB_BAF_L85A2_RIS_G","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","UK3CB_BAF_TA31F_Hornbill",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_g"],["UK3CB_BAF_Javelin_Slung_Tube","","","",[],[],""],[],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["UK3CB_BAF_V_Osprey_Rifleman_F",[["ACRE_PRC343",1],["ACE_IR_Strobe_Item",1],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",2,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1],["UK3CB_BAF_556_30Rnd",10,30],["UK3CB_BAF_SmokeShellRed",2,1]]],[],"UK3CB_BAF_H_Mk7_Net_B","UK3CB_BAF_G_Tactical_Grey",["UK3CB_BAF_Javelin_CLU","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infMortar = ["[Infanterie] Artilleur mortier", [["UK3CB_BAF_L85A2_RIS_G","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","UK3CB_BAF_TA31F_Hornbill",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_g"],["UK3CB_BAF_M6","","","",["UK3CB_BAF_1Rnd_60mm_Mo_Shells",1],[],""],[],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["UK3CB_BAF_M6_RangeTable",1]]],["UK3CB_BAF_V_Osprey_Rifleman_F",[["ACRE_PRC343",1],["ACE_IR_Strobe_Item",1],["UK3CB_BAF_SmokeShell",4,1],["HandGrenade",2,1],["UK3CB_BAF_556_30Rnd",6,30],["ACE_Chemlight_IR",1,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellBlue",1,1]]],["UK3CB_BAF_B_Bergen_MTP_Rifleman_L_C",[["UK3CB_BAF_1Rnd_60mm_Mo_Smoke_White",2,1],["UK3CB_BAF_1Rnd_60mm_Mo_Shells",2,1]]],"UK3CB_BAF_H_Mk7_Net_B","UK3CB_BAF_G_Tactical_Grey",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infMortarAssist = ["[Infanterie] Assistant mortier",  [["UK3CB_BAF_L85A2_RIS_G","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_LDS",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_g"],[],[],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["UK3CB_BAF_M6_RangeTable",1]]],["UK3CB_BAF_V_Osprey_Rifleman_F",[["ACRE_PRC343",1],["ACE_IR_Strobe_Item",1],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1],["UK3CB_BAF_556_30Rnd",8,30],["UK3CB_BAF_SmokeShellRed",1,1]]],["UK3CB_BAF_B_Bergen_MTP_Rifleman_L_C",[["UK3CB_BAF_1Rnd_60mm_Mo_Shells",4,1],["UK3CB_BAF_1Rnd_60mm_Mo_Smoke_White",4,1],["UK3CB_BAF_1Rnd_60mm_Mo_Smoke_Red",1,1]]],"UK3CB_BAF_H_Mk7_Net_B","UK3CB_BAF_G_Tactical_Grey",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];

// NRBC
private _infNrbcLead = ["[NRBC] Chef d'équipe", [["rhs_weap_m4a1","rhsusf_acc_nt4_black","rhsusf_acc_anpeq15_wmx","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip2_tan"],[],[],["U_B_CBRN_Suit_01_MTP_F",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",4],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["rhsusf_plateframe_teamleader",[["rhs_mag_30Rnd_556x45_M855A1_PMAG",10,30],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellBlue",1,1],["B_IR_Grenade",1,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1],["ACE_CTS9",2,1]]],["UK3CB_BAF_B_Bergen_TAN_SL_A",[["ACRE_PRC152",1],["ACRE_PRC117F",1]]],"rhsusf_opscore_bk","G_AirPurifyingRespirator_01_F",["UK3CB_BAF_Soflam_Laserdesignator","","","",[],[],""],["ItemMap","","","ItemCompass","ChemicalDetector_01_watch_F","rhsusf_ANPVS_15"]]];
private _infNrbcOperator = ["[NRBC] Opérateur NRBC", [["rhs_weap_m4a1","rhsusf_acc_nt4_black","rhsusf_acc_anpeq15_wmx","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip2_tan"],[],["UK3CB_BAF_L117A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["U_B_CBRN_Suit_01_MTP_F",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",4],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["rhsusf_plateframe_teamleader",[["rhs_mag_30Rnd_556x45_M855A1_PMAG",10,30],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",1,1],["ACE_Chemlight_IR",1,1],["ACE_CTS9",2,1],["UK3CB_BAF_9_15Rnd",2,15]]],[],"rhsusf_opscore_rg_cover","G_AirPurifyingRespirator_01_F",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _infNrbcMg = ["[NRBC] Mitrailleur", [["rhs_weap_m249_pip_S","","rhsusf_acc_anpeq15side","rhsusf_acc_su230a",["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",200],[],"rhsusf_acc_grip1"],[],[],["U_B_CBRN_Suit_01_MTP_F",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",4],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["rhsusf_mbav_mg",[["UK3CB_BAF_SmokeShell",4,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1],["ACE_CTS9",2,1],["rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",4,100]]],[],"rhsusf_opscore_mc_cover","G_AirPurifyingRespirator_01_F",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _infNrbcTp = ["[NRBC] TP", [["UK3CB_BAF_L129A1","UK3CB_BAF_Silencer_L115A3","rhsusf_acc_anpeq15side","RKSL_optic_PMII_312",["UK3CB_BAF_762_L42A1_20Rnd",20],[],"UK3CB_underbarrel_acc_fgrip_bipod"],[],["UK3CB_BAF_L117A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["U_B_CBRN_Suit_01_MTP_F",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",4],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_RangeCard",1]]],["rhsusf_plateframe_machinegunner",[["UK3CB_BAF_SmokeShell",2,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",1,1],["ACE_Chemlight_IR",1,1],["ACE_CTS9",1,1],["UK3CB_BAF_9_15Rnd",2,15],["UK3CB_BAF_762_L42A1_20Rnd",7,20]]],[],"rhsusf_opscore_fg","G_AirPurifyingRespirator_01_F",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _infNrbcGl = ["[NRBC] Grenadier", [["rhs_weap_m4a1_m203","rhsusf_acc_nt4_black","rhsusf_acc_anpeq15side","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],["rhs_mag_M433_HEDP",1],"rhsusf_acc_grip_m203_blk"],[],["UK3CB_BAF_L117A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["U_B_CBRN_Suit_01_MTP_F",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",4],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["rhsusf_plateframe_grenadier",[["rhs_mag_30Rnd_556x45_M855A1_PMAG",8,30],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",1,1],["ACE_Chemlight_IR",1,1],["ACE_CTS9",2,1],["UK3CB_BAF_9_15Rnd",2,15]]],["B_AssaultPack_cbr",[["rhs_mag_M433_HEDP",14,1],["rhs_mag_m714_White",4,1],["rhs_mag_m713_Red",2,1]]],"rhsusf_opscore_coy_cover","G_AirPurifyingRespirator_01_F",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _infNrbcEod = ["[NRBC] EOD", [["rhs_weap_m4a1","rhsusf_acc_nt4_black","rhsusf_acc_anpeq15_wmx","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip2_tan"],[],["ACE_VMH3","","","",[],[],""],["U_B_CBRN_Suit_01_MTP_F",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",4],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["rhsusf_plateframe_teamleader",[["rhs_mag_30Rnd_556x45_M855A1_PMAG",10,30],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",1,1],["ACE_Chemlight_IR",1,1],["ACE_CTS9",2,1]]],["UK3CB_BAF_B_Bergen_TAN_Rifleman_B",[["ACE_Clacker",1],["ACE_DefusalKit",2],["ACE_EntrenchingTool",1],["ACE_wirecutter",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["DemoCharge_Remote_Mag",2,1]]],"rhsusf_opscore_paint","G_AirPurifyingRespirator_01_F",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _infNrbcMedic = ["[NRBC] Medic", [["rhs_weap_m4a1","rhsusf_acc_nt4_black","rhsusf_acc_anpeq15_wmx","UK3CB_BAF_TA31F",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip2_tan"],[],["UK3CB_BAF_L117A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["U_B_CBRN_Suit_01_MTP_F",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",4],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["rhsusf_plateframe_teamleader",[["rhs_mag_30Rnd_556x45_M855A1_PMAG",8,30],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",1,1],["ACE_Chemlight_IR",1,1],["ACE_CTS9",2,1],["UK3CB_BAF_9_15Rnd",2,15]]],["UK3CB_BAF_B_Kitbag_MTP",[["ACE_splint",6],["ACE_epinephrine",6],["ACE_morphine",6],["ACE_packingBandage",10],["ACE_elasticBandage",10],["ACE_tourniquet",4],["ACE_salineIV",6],["ACE_salineIV_250",8],["ACE_salineIV_500",8],["ACE_surgicalKit",1]]],"rhsusf_opscore_rg_cover","G_AirPurifyingRespirator_01_F",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _infNrbcFac = ["[NRBC] FAC", [["rhs_weap_hk416d10_LMT","rhsusf_acc_nt4_black","rhsusf_acc_anpeq15_wmx","rhsusf_acc_g33_xps3",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip2"],[],[],["U_B_CBRN_Suit_01_MTP_F",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",4],["ACRE_PRC148",1],["ACE_tourniquet",2],["ACE_MapTools",1]]],["rhsusf_mbav_rifleman",[["UK3CB_BAF_SmokeShell",4,1],["B_IR_Grenade",2,1],["HandGrenade",2,1],["ACE_Chemlight_IR",2,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",8,30]]],["UK3CB_BAF_B_Bergen_TAN_JTAC_A",[["ACRE_PRC152",1],["ACRE_PRC117F",1]]],"rhsusf_opscore_bk","G_AirPurifyingRespirator_01_F",["UK3CB_BAF_Soflam_Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];


// SAS
private _sasLead = ["[SAS] Chef d'équipe", [["rhs_weap_m4a1","rhsusf_acc_nt4_black","rhsusf_acc_anpeq15_wmx","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip2_tan"],[],[],["rhs_uniform_g3_blk",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",4],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_splint",1]]],["rhsusf_plateframe_teamleader",[["rhs_mag_30Rnd_556x45_M855A1_PMAG",10,30],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellBlue",1,1],["B_IR_Grenade",1,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1],["ACE_CTS9",2,1]]],["UK3CB_BAF_B_Bergen_TAN_SL_A",[["ACRE_PRC152",1],["ACRE_PRC117F",1]]],"rhsusf_opscore_bk_pelt","rhsusf_shemagh2_od",["UK3CB_BAF_Soflam_Laserdesignator","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _sasOperator = ["[SAS] Opérateur", [["rhs_weap_m4a1","rhsusf_acc_nt4_black","rhsusf_acc_anpeq15_wmx","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip2_tan"],[],["UK3CB_BAF_L117A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["rhs_uniform_g3_blk",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",4],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_splint",1],["ACRE_PRC152",1]]],["rhsusf_plateframe_teamleader",[["rhs_mag_30Rnd_556x45_M855A1_PMAG",10,30],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",1,1],["ACE_Chemlight_IR",1,1],["ACE_CTS9",2,1],["UK3CB_BAF_9_15Rnd",2,15]]],[],"rhsusf_opscore_paint_pelt_nsw","rhsusf_shemagh2_od",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _sasMg = ["[SAS] Mitrailleur", [["rhs_weap_m249_pip_S","","rhsusf_acc_anpeq15side","rhsusf_acc_su230a",["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",200],[],"rhsusf_acc_grip1"],[],[],["rhs_uniform_g3_blk",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",4],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_splint",1],["ACRE_PRC152",1]]],["rhsusf_mbav_mg",[["UK3CB_BAF_SmokeShell",4,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1],["ACE_CTS9",2,1],["rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",4,100]]],[],"rhsusf_opscore_paint_pelt_nsw","rhsusf_shemagh2_od",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _sasTp = ["[SAS] TP", [["UK3CB_BAF_L129A1","UK3CB_BAF_Silencer_L115A3","rhsusf_acc_anpeq15side","RKSL_optic_PMII_312",["UK3CB_BAF_762_L42A1_20Rnd",20],[],"UK3CB_underbarrel_acc_fgrip_bipod"],[],["UK3CB_BAF_L117A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["rhs_uniform_g3_blk",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",4],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_splint",1],["ACRE_PRC152",1],["ACE_RangeCard",1]]],["rhsusf_plateframe_machinegunner",[["UK3CB_BAF_SmokeShell",2,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",1,1],["ACE_Chemlight_IR",1,1],["ACE_CTS9",1,1],["UK3CB_BAF_9_15Rnd",2,15],["UK3CB_BAF_762_L42A1_20Rnd",7,20]]],["B_AssaultPack_cbr",[["UK3CB_BAF_MaxiKite",1]]],"rhsusf_opscore_rg_cover_pelt","G_Bandanna_oli",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _sasGl = ["[SAS] Grenadier", [["rhs_weap_m4a1_m203","rhsusf_acc_nt4_black","rhsusf_acc_anpeq15side","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],["rhs_mag_M433_HEDP",1],"rhsusf_acc_grip_m203_blk"],[],["UK3CB_BAF_L117A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["rhs_uniform_g3_blk",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",4],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_splint",1],["ACRE_PRC152",1]]],["rhsusf_plateframe_grenadier",[["rhs_mag_30Rnd_556x45_M855A1_PMAG",8,30],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",1,1],["ACE_Chemlight_IR",1,1],["ACE_CTS9",2,1],["UK3CB_BAF_9_15Rnd",2,15]]],["B_AssaultPack_cbr",[["rhs_mag_M433_HEDP",14,1],["rhs_mag_m714_White",4,1],["rhs_mag_m713_Red",2,1]]],"rhsusf_opscore_bk_pelt","rhsusf_shemagh2_od",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _sasEod = ["[SAS] EOD", [["rhs_weap_m4a1","rhsusf_acc_nt4_black","rhsusf_acc_anpeq15_wmx","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip2_tan"],[],["ACE_VMH3","","","",[],[],""],["rhs_uniform_g3_blk",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",4],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_splint",1],["ACRE_PRC152",1]]],["rhsusf_plateframe_teamleader",[["rhs_mag_30Rnd_556x45_M855A1_PMAG",10,30],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",1,1],["ACE_Chemlight_IR",1,1],["ACE_CTS9",2,1]]],["UK3CB_BAF_B_Bergen_TAN_Rifleman_B",[["ACE_Clacker",1],["ACE_DefusalKit",1],["ACE_EntrenchingTool",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["ACE_wirecutter",1],["DemoCharge_Remote_Mag",2,1]]],"rhsusf_opscore_paint_pelt_nsw","rhsusf_shemagh2_od",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _sasMedic = ["[SAS] Médecin", [["rhs_weap_m4a1","rhsusf_acc_nt4_black","rhsusf_acc_anpeq15_wmx","UK3CB_BAF_TA31F",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip2_tan"],[],["UK3CB_BAF_L117A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["rhs_uniform_g3_blk",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",4],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_splint",1],["ACRE_PRC152",1]]],["rhsusf_plateframe_teamleader",[["rhs_mag_30Rnd_556x45_M855A1_PMAG",8,30],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",1,1],["ACE_Chemlight_IR",1,1],["ACE_CTS9",2,1],["UK3CB_BAF_9_15Rnd",2,15]]],["UK3CB_BAF_B_Kitbag_MTP",[["ACE_splint",6],["ACE_epinephrine",6],["ACE_morphine",6],["ACE_packingBandage",10],["ACE_elasticBandage",10],["ACE_tourniquet",4],["ACE_salineIV",6],["ACE_salineIV_250",8],["ACE_salineIV_500",8],["ACE_surgicalKit",1]]],"rhsusf_opscore_paint_pelt_nsw","rhsusf_shemagh2_od",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _sasFac = ["[SAS] FAC", [["rhs_weap_hk416d10_LMT","rhsusf_acc_nt4_black","rhsusf_acc_anpeq15_wmx","rhsusf_acc_g33_xps3",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip2"],[],[],["rhs_uniform_g3_blk",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",4],["ACRE_PRC148",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_splint",1]]],["rhsusf_mbav_rifleman",[["UK3CB_BAF_SmokeShell",4,1],["B_IR_Grenade",2,1],["HandGrenade",2,1],["ACE_Chemlight_IR",2,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",8,30]]],["UK3CB_BAF_B_Bergen_TAN_JTAC_A",[["ACRE_PRC152",1],["ACRE_PRC117F",1]]],"rhsusf_opscore_bk_pelt","G_Bandanna_blk",["UK3CB_BAF_Soflam_Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _sasFirstMan = ["[SAS] First Man", [["UK3CB_BAF_L92A1","","","rhsusf_acc_T1_low",["UK3CB_BAF_9_30Rnd",30],[],""],[],["UK3CB_BAF_L117A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["rhs_uniform_g3_blk",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",4],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_splint",1],["ACRE_PRC152",1]]],["rhsusf_plateframe_medic",[["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",1,1],["ACE_Chemlight_IR",1,1],["ACE_CTS9",2,1],["UK3CB_BAF_9_15Rnd",2,15],["UK3CB_BAF_9_30Rnd",10,30]]],["UK3CB_BAF_B_Kitbag_MTP",[["ACE_Chemlight_HiRed",10,1],["ACE_Chemlight_HiGreen",10,1],["ACE_CTS9",6,1]]],"rhsusf_opscore_paint_pelt_nsw","rhsusf_shemagh2_od",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _sasBreacher = ["[SAS] Breacher", [["UK3CB_BAF_L128A1","","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_EOT552",["UK3CB_BAF_12G_Slugs",8],[],""],[],["UK3CB_BAF_L105A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["rhs_uniform_g3_blk",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",4],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_splint",1],["ACRE_PRC152",1]]],["rhsusf_plateframe_machinegunner",[["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",1,1],["ACE_Chemlight_IR",1,1],["ACE_CTS9",2,1],["UK3CB_BAF_9_15Rnd",4,15],["UK3CB_BAF_12G_Pellets",6,8],["UK3CB_BAF_12G_Slugs",6,8]]],[],"rhsusf_opscore_paint_pelt_nsw","rhsusf_shemagh2_od",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];

private _sasSniper = ["[SAS] Sniper", [["UK3CB_BAF_L115A3_DE","UK3CB_BAF_Silencer_L115A3","","RKSL_optic_PMII_525",["UK3CB_BAF_338_5Rnd",5],[],"UK3CB_underbarrel_acc_bipod"],[],["UK3CB_BAF_L117A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["UK3CB_BAF_U_CombatUniform_MTP_Ghillie_RM",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",4],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_splint",1],["ACRE_PRC152",1],["ACE_RangeCard",1]]],["rhsusf_plateframe_machinegunner",[["UK3CB_BAF_SmokeShell",2,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",1,1],["ACE_Chemlight_IR",1,1],["ACE_CTS9",1,1],["UK3CB_BAF_9_15Rnd",4,15],["UK3CB_BAF_338_5Rnd",10,5]]],["B_AssaultPack_cbr",[["ACE_ATragMX",1],["ACE_Tripod",1],["UK3CB_BAF_MaxiKite",1]]],"rhsusf_opscore_paint_pelt_nsw","",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _sasSpotter = ["[SAS] Spotteur", [["UK3CB_BAF_L129A1","UK3CB_BAF_Silencer_L115A3","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_PMII_312_sunshade",["UK3CB_BAF_762_L42A1_20Rnd",20],[],"UK3CB_underbarrel_acc_fgrip_bipod"],[],["UK3CB_BAF_L117A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["UK3CB_BAF_U_CombatUniform_MTP_Ghillie_RM",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",4],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_splint",1],["ACRE_PRC152",1],["ACE_RangeCard",1]]],["rhsusf_plateframe_machinegunner",[["UK3CB_BAF_SmokeShell",2,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",1,1],["ACE_Chemlight_IR",1,1],["ACE_CTS9",1,1],["UK3CB_BAF_9_15Rnd",2,15],["UK3CB_BAF_762_L42A1_20Rnd",7,20]]],["B_AssaultPack_cbr",[["ACE_EntrenchingTool",1],["ACE_Kestrel4500",1],["ACE_ATragMX",1],["ACE_RangeCard",1],["ACE_Tripod",1],["UK3CB_BAF_MaxiKite",1]]],"rhsusf_opscore_paint_pelt_nsw","",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];

// Royal Tanks
private _tankCrewman = ["[Royal Tank] Crewman", [["UK3CB_BAF_L22A2","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_EOT552",["UK3CB_BAF_556_30Rnd",30],[],""],[],[],["UK3CB_BAF_U_CrewmanCoveralls_RTR",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["UK3CB_BAF_V_Osprey_Rifleman_A",[["ToolKit",1],["ACE_IR_Strobe_Item",1],["ACRE_PRC343",1],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",2,1],["ACE_Chemlight_IR",1,1],["HandGrenade",2,1],["UK3CB_BAF_556_30Rnd",4,30]]],[],"UK3CB_BAF_H_CrewHelmet_A","",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter",""]]];

// RAF
// Helo
private _rafHeloPilot = ["[Royal Air Force] Pilote hélico", [["UK3CB_BAF_L22A2","","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_EOT552",["UK3CB_BAF_556_30Rnd",30],[],""],[],["UK3CB_BAF_L105A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["UK3CB_BAF_U_HeliPilotCoveralls_RAF",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["UK3CB_BAF_V_Pilot_A",[["ACE_IR_Strobe_Item",1],["ACRE_PRC148",1],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",2,1],["ACE_Chemlight_IR",1,1],["HandGrenade",2,1],["UK3CB_BAF_556_30Rnd",4,30],["UK3CB_BAF_9_15Rnd",2,15]]],[],"rhsusf_hgu56p_visor_green","rhsusf_shemagh_od",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];
private _rafHeloGunner = ["[Royal Air Force] Tireur hélico", [["UK3CB_BAF_L22A2","","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_EOT552",["UK3CB_BAF_556_30Rnd",30],[],""],[],["UK3CB_BAF_L105A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["UK3CB_BAF_U_HeliPilotCoveralls_RAF",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["UK3CB_BAF_V_Pilot_A",[["ACE_IR_Strobe_Item",1],["ACRE_PRC148",1],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",2,1],["ACE_Chemlight_IR",1,1],["HandGrenade",2,1],["UK3CB_BAF_556_30Rnd",4,30],["UK3CB_BAF_9_15Rnd",2,15]]],[],"rhsusf_hgu56p_visor_green","rhsusf_shemagh_od",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]];

// Planes
private _rafC130Pilot = ["[Royal Air Force] Pilote Hercules", [["UK3CB_BAF_L91A1","","","rhsusf_acc_eotech_xps3",["UK3CB_BAF_9_30Rnd",30],[],""],[],[],["UK3CB_BAF_U_HeliPilotCoveralls_RAF",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["UK3CB_BAF_V_Pilot_A",[["ACRE_PRC343",1],["ACE_IR_Strobe_Item",1],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",1,1],["UK3CB_BAF_SmokeShellRed",1,1],["B_IR_Grenade",1,1],["HandGrenade",1,1],["ACE_Chemlight_IR",1,1],["UK3CB_BAF_9_30Rnd",6,30]]],[],"UK3CB_BAF_H_Earphone","UK3CB_BAF_G_Tactical_Grey",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]];
private _rafF35Pilot = ["[Royal Air Force] Pilote F-35", [[],[],["UK3CB_BAF_L117A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["U_I_pilotCoveralls",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACRE_PRC343",1],["UK3CB_BAF_SmokeShell",2,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellBlue",1,1],["ACE_Chemlight_IR",1,1],["UK3CB_BAF_9_15Rnd",2,15]]],[],["B_Parachute",[]],"H_PilotHelmetFighter_O","UK3CB_BAF_G_Tactical_Grey",[],["ItemMap","","","ItemCompass","ACE_Altimeter",""]]];
private _rafF35Pilot2 = ["[Royal Air Force] Pilote F-35", [[],[],["UK3CB_BAF_L117A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["U_I_pilotCoveralls",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACRE_PRC343",1],["UK3CB_BAF_SmokeShell",2,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShellBlue",1,1],["ACE_Chemlight_IR",1,1],["UK3CB_BAF_9_15Rnd",2,15]]],[],["B_Parachute",[]],"FIR_JHMCS_Type2","",[],["ItemMap","","","ItemCompass","ACE_Altimeter",""]]];

{
	_x params ["_name", "_loadout"];
	[_name, _loadout] call ace_arsenal_fnc_addDefaultLoadout;
} forEach [
	_brief,
	_briefTank,
	_briefingRaf,
	_birefingSas,
	_infCds,
	_infJtac,
	_infRadio,
	_infMedic,
	_infGenieEOD,
	_infRifleman,
	_infTlAssault,
	_infGl,
	_infHeavyMg,
	_infMg,
	_infTlSupport,
	_infMarksman,
	_infAt,
	_infAa,
	_infHeavyAt,
	_infMortar,
	_infMortarAssist,
	_infNrbcLead,
	_infNrbcOperator,
	_infNrbcMg,
	_infNrbcTp,
	_infNrbcGl,
	_infNrbcEod,
	_infNrbcMedic,
	_infNrbcFac,
	_sasLead,
	_sasOperator,
	_sasMg,
	_sasTp,
	_sasGl,
	_sasEod,
	_sasMedic,
	_sasFac,
	_sasFirstMan,
	_sasBreacher,
	_sasSniper,
	_sasSpotter,
	_tankCrewman
];