// Base
private _brief = ["Briefing", [[],[],[],["UK3CB_BAF_U_RolledUniform_MTP",[]],[],[],"UK3CB_BAF_H_Beret_PR","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]];
private _briefTank = ["Briefing Royal Tanks", [[],[],[],["UK3CB_BAF_U_Smock_MTP",[]],[],[],"UK3CB_BAF_H_Beret_RTR","UK3CB_BAF_G_Tactical_Black",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]];
private _briefingRaf = ["Briefing RAF", [[],[],[],["UK3CB_BAF_U_HeliPilotCoveralls_RAF",[]],[],[],"UK3CB_BAF_H_Beret_RAF","G_Aviator",[],["ItemMap","","","ItemCompass","ItemWatch",""]]];
private _birefingSas = ["Briefing SAS", [[],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["ARD_Tan_Camo_Cyre_TSB",[]],["Belt_gbrs",[["ACE_CableTie",2],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],[],"H_Cap_khaki_specops_UK","UK3CB_BAF_G_Tactical_Grey",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]];

// Infanterie
private _infCds = ["[Infanterie] Chef de section", [["UK3CB_BAF_L85A3","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","UK3CB_BAF_TA31F_Hornbill",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_g"],[],["UK3CB_BAF_L131A1","","","",["UK3CB_BAF_9_17Rnd",17],[],""],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_IR_Strobe_Item",1],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_Flashlight_MX991",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACRE_PRC343",1]]],["UK3CB_BAF_V_Osprey_SL_D",[["ACRE_PRC148",1],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",1,1],["UK3CB_BAF_SmokeShellRed",1,1],["B_IR_Grenade",1,1],["ACE_Chemlight_IR",2,1],["rhs_mag_m67",2,1],["UK3CB_BAF_556_30Rnd",8,30],["UK3CB_BAF_9_17Rnd",2,17]]],["UK3CB_BAF_B_Bergen_MTP_SL_L_A",[["ACRE_PRC117F",1]]],"UK3CB_BAF_H_Mk7_Camo_D","UK3CB_BAF_G_Tactical_Grey",[],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infJtac = ["[Infanterie] FAC",  [["UK3CB_BAF_L85A3","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","UK3CB_BAF_TA31F_Hornbill",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_g"],[],[],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_IR_Strobe_Item",1],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_Flashlight_MX991",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACRE_PRC148",1]]],["UK3CB_BAF_V_Osprey_SL_A",[["UK3CB_BAF_556_30Rnd",8,30],["UK3CB_BAF_SmokeShell",6,1],["UK3CB_BAF_SmokeShellBlue",2,1],["B_IR_Grenade",1,1],["ACE_Chemlight_IR",2,1],["HandGrenade",2,1]]],["UK3CB_BAF_B_Bergen_MTP_JTAC_H_A",[["ACE_EntrenchingTool",1],["ACRE_PRC117F",1]]],"UK3CB_BAF_H_Mk7_Camo_D","UK3CB_BAF_G_Tactical_Grey",["UK3CB_BAF_Soflam_Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infMedic = ["[Infanterie] Médecin", [["UK3CB_BAF_L85A3","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","UK3CB_BAF_TA31F_Hornbill",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_g"],[],[],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_IR_Strobe_Item",1],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_Flashlight_MX991",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACRE_PRC343",1]]],["UK3CB_BAF_V_Osprey_Medic_D",[["UK3CB_BAF_556_30Rnd",8,30],["UK3CB_BAF_SmokeShell",6,1],["UK3CB_BAF_SmokeShellBlue",2,1],["HandGrenade",2,1],["ACE_Chemlight_IR",2,1]]],["UK3CB_BAF_B_Bergen_MTP_Medic_H_B",[["ACE_splint",8],["ACE_epinephrine",10],["ACE_morphine",10],["ACE_packingBandage",15],["ACE_elasticBandage",15],["ACE_tourniquet",4],["ACE_salineIV",10],["ACE_salineIV_250",8],["ACE_salineIV_500",10],["ACE_EntrenchingTool",1],["ACE_surgicalKit",1],["ACE_quikclot",10]]],"UK3CB_BAF_H_Mk7_Camo_D","UK3CB_BAF_G_Tactical_Grey",[],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infGenieEOD = ["[Infanterie] EOD", [["UK3CB_BAF_L85A3","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","UK3CB_BAF_TA31F_Hornbill",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_g"],[],[],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_IR_Strobe_Item",1],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_Flashlight_MX991",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACRE_PRC343",1]]],["UK3CB_BAF_V_Osprey_Rifleman_E",[["UK3CB_BAF_556_30Rnd",8,30],["UK3CB_BAF_SmokeShell",6,1],["UK3CB_BAF_SmokeShellBlue",2,1],["B_IR_Grenade",1,1],["HandGrenade",4,1],["ACE_Chemlight_IR",2,1]]],["UK3CB_BAF_B_Bergen_MTP_Sapper_L_A",[["ACE_Clacker",1],["ACE_DefusalKit",1],["ACE_EntrenchingTool",1],["ACE_wirecutter",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["rhsusf_m112x4_mag",2,1],["rhsusf_m112_mag",2,1]]],"UK3CB_BAF_H_Mk7_Camo_D","UK3CB_BAF_G_Tactical_Grey",[],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infRifleman = ["[Infanterie] Fusilier", [["UK3CB_BAF_L85A3","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","UK3CB_BAF_TA31F_Hornbill",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_g"],[],[],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_IR_Strobe_Item",1],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_Flashlight_MX991",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACRE_PRC343",1]]],["UK3CB_BAF_V_Osprey_Rifleman_F",[["UK3CB_BAF_SmokeShell",4,1],["ACE_Chemlight_IR",2,1],["HandGrenade",2,1],["UK3CB_BAF_SmokeShellBlue",1,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_556_30Rnd",8,30]]],[],"UK3CB_BAF_H_Mk7_Camo_D","UK3CB_BAF_G_Tactical_Grey",[],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infGl = ["[Infanterie] Grenadier", [["UK3CB_BAF_L85A3_UGL","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","UK3CB_BAF_TA31F_Hornbill",["UK3CB_BAF_556_30Rnd",30],["UK3CB_BAF_1Rnd_HE_Grenade_Shell",1],""],[],[],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_IR_Strobe_Item",1],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_Flashlight_MX991",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACRE_PRC343",1]]],["UK3CB_BAF_V_Osprey_Grenadier_A",[["UK3CB_BAF_556_30Rnd",8,30],["UK3CB_BAF_1Rnd_HE_Grenade_Shell",13,1],["UK3CB_BAF_1Rnd_Smoke_Grenade_shell",4,1],["UK3CB_BAF_1Rnd_SmokeRed_Grenade_shell",2,1],["UGL_FlareCIR_F",1,1]]],[],"UK3CB_BAF_H_Mk7_Camo_D","UK3CB_BAF_G_Tactical_Grey",[],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infHeavyMg = ["[Infanterie] Mitrailleur lourd", [["UK3CB_BAF_L7A2","","","",["UK3CB_BAF_762_200Rnd",200],[],""],[],["UK3CB_BAF_L131A1","","","",["UK3CB_BAF_9_17Rnd",17],[],""],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_IR_Strobe_Item",1],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_Flashlight_MX991",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACRE_PRC343",1]]],["UK3CB_BAF_V_Osprey_MG_B",[["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",2,1],["ACE_Chemlight_IR",2,1],["UK3CB_BAF_762_100Rnd",3,100],["UK3CB_BAF_9_17Rnd",2,17]]],[],"UK3CB_BAF_H_Mk7_Scrim_C","UK3CB_BAF_G_Tactical_Grey",[],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infMg = ["[Infanterie] Mitrailleur", [["UK3CB_BAF_L110A2RIS","","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_LDS",["UK3CB_BAF_556_200Rnd",200],[],""],[],["UK3CB_BAF_L131A1","","","",["UK3CB_BAF_9_17Rnd",17],[],""],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_IR_Strobe_Item",1],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_Flashlight_MX991",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACRE_PRC343",1]]],["UK3CB_BAF_V_Osprey_MG_B",[["UK3CB_BAF_556_100Rnd",3,100],["UK3CB_BAF_SmokeShell",6,1],["UK3CB_BAF_SmokeShellBlue",2,1],["HandGrenade",2,1],["ACE_Chemlight_IR",2,1],["UK3CB_BAF_9_17Rnd",2,17]]],[],"UK3CB_BAF_H_Mk7_Scrim_C","UK3CB_BAF_G_Tactical_Grey",[],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infMarksman = ["[Infanterie] Marksman", [["UK3CB_BAF_L129A1","","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_PMII_312",["UK3CB_BAF_762_L42A1_20Rnd",20],[],"UK3CB_underbarrel_acc_bipod"],[],["UK3CB_BAF_L131A1","","","",["UK3CB_BAF_9_17Rnd",17],[],""],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_IR_Strobe_Item",1],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_Flashlight_MX991",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACRE_PRC343",1]]],["UK3CB_BAF_V_Osprey_Marksman_A",[["UK3CB_BAF_762_L42A1_20Rnd",8,20],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",1,1],["B_IR_Grenade",1,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1]]],["UK3CB_BAF_B_Bergen_MTP_Rifleman_H_C",[["ACE_Tripod",1],["ACE_EntrenchingTool",1],["ACE_RangeCard",1],["UK3CB_BAF_MaxiKite",1],["UK3CB_BAF_9_17Rnd",2,17]]],"UK3CB_BAF_H_Mk7_Scrim_A","UK3CB_BAF_G_Tactical_Grey",[],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infHeavyAt = ["[Infanterie] Spécialiste AT", [["UK3CB_BAF_L85A3","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","UK3CB_BAF_TA31F_Hornbill",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_g"],["UK3CB_BAF_Javelin_Slung_Tube","","","",[],[],""],[],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_IR_Strobe_Item",1],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_Flashlight_MX991",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACRE_PRC343",1]]],["UK3CB_BAF_V_Osprey_Rifleman_F",[["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",2,1],["UK3CB_BAF_556_30Rnd",8,30]]],[],"UK3CB_BAF_H_Mk7_Camo_D","UK3CB_BAF_G_Tactical_Grey",["UK3CB_BAF_Javelin_CLU","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infMortar = ["[Infanterie] Artilleur mortier", [["UK3CB_BAF_L85A3","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","UK3CB_BAF_TA31F_Hornbill",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_g"],["UK3CB_BAF_M6","","","",["UK3CB_BAF_1Rnd_60mm_Mo_Shells",1],[],""],[],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_IR_Strobe_Item",1],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_Flashlight_MX991",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACRE_PRC343",1]]],["UK3CB_BAF_V_Osprey_Rifleman_F",[["UK3CB_BAF_556_30Rnd",6,30],["UK3CB_BAF_SmokeShell",2,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1]]],["UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D",[["UK3CB_BAF_1Rnd_60mm_Mo_Shells",4,1],["UK3CB_BAF_1Rnd_60mm_Mo_Smoke_White",1,1]]],"UK3CB_BAF_H_Mk7_Camo_D","UK3CB_BAF_G_Tactical_Grey",[],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];
private _infMortarAssist = ["[Infanterie] Assistant mortier", [["UK3CB_BAF_L85A2_RIS_G","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_LDS",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_g"],[],[],["UK3CB_BAF_U_CombatUniform_MTP",[["ACE_splint",1],["ACE_epinephrine",1],["ACE_morphine",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["UK3CB_BAF_M6_RangeTable",1]]],["UK3CB_BAF_V_Osprey_Rifleman_F",[["ACRE_PRC343",1],["ACE_IR_Strobe_Item",1],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",1,1],["HandGrenade",2,1],["ACE_Chemlight_IR",1,1],["UK3CB_BAF_556_30Rnd",8,30],["UK3CB_BAF_SmokeShellRed",1,1]]],["UK3CB_BAF_B_Bergen_MTP_Rifleman_L_C",[["UK3CB_BAF_1Rnd_60mm_Mo_Shells",4,1],["UK3CB_BAF_1Rnd_60mm_Mo_Smoke_White",4,1],["UK3CB_BAF_1Rnd_60mm_Mo_Smoke_Red",1,1]]],"UK3CB_BAF_H_Mk7_Net_B","UK3CB_BAF_G_Tactical_Grey",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","UK3CB_BAF_HMNVS"]]];

// NRBC
private _infNrbcOperator = ["[NRBC] Opérateur NRBC", [["rhs_weap_m4a1_mstock","rhsusf_acc_rotex5_grey","rhsusf_acc_anpeq15_bk","rhsusf_acc_g33_xps3",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip3"],[],["UK3CB_BAF_L105A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["U_C_CBRN_Suit_01_Blue_F",[["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",2],["ACE_splint",1],["ACRE_PRC152",1],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_MapTools",1]]],["rhsusf_mbav_rifleman",[["UK3CB_BAF_9_15Rnd",1,15],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30],["UK3CB_BAF_SmokeShellBlue",1,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShell",4,1],["HandGrenade",2,1],["ACE_CTS9",2,1],["ACE_Chemlight_IR",1,1]]],["B_AssaultPack_cbr",[]],"rhsusf_opscore_fg","G_AirPurifyingRespirator_01_F",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","JAS_GPNVG18_Tan"]]];

// SAS
private _sasLead = ["[SAS] Chef d'équipe", [["rhs_weap_m4a1_mstock","rhsusf_acc_nt4_black","rhsusf_acc_anpeq15_light","rhsusf_acc_g33_xps3",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip3"],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["ARD_MC_Camo_Cyre_SS",[["ACE_IR_Strobe_Item",2],["ACE_morphine",2],["ACE_epinephrine",1],["ACE_splint",1],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1]]],["Crye_AVS_3_3_RG",[["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30],["rhsusf_mag_17Rnd_9x19_FMJ",1,17],["UK3CB_BAF_SmokeShellBlue",1,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShell",4,1],["B_IR_Grenade",1,1],["HandGrenade",1,1],["ACE_CTS9",2,1],["ACE_Chemlight_IR",1,1]]],[],"rhsusf_opscore_mc_cover_pelt_nsw","UK3CB_BAF_G_Tactical_Grey",["UK3CB_BAF_Soflam_Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","JAS_GPNVG18_Tan"]]];
private _sasOperator = ["[SAS] Opérateur", [["rhs_weap_m4a1_mstock","rhsusf_acc_rotex5_grey","rhsusf_acc_anpeq15_bk","rhsusf_acc_g33_xps3",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip3"],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["ARD_MC_Camo_Cyre_SS",[["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",2],["ACE_splint",1],["ACRE_PRC152",1],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2]]],["Crye_AVS_1_3_RG",[["rhsusf_mag_17Rnd_9x19_FMJ",1,17],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",1,1],["UK3CB_BAF_SmokeShellRed",1,1],["HandGrenade",2,1],["ACE_CTS9",2,1],["ACE_Chemlight_IR",2,1]]],[],"rhsusf_opscore_mc_cover_pelt_cam","UK3CB_BAF_G_Tactical_Grey",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","JAS_GPNVG18_Tan"]]];
private _sasMg = ["[SAS] Mitrailleur", [["rhs_weap_m249_pip_S","rhsusf_acc_rotex5_grey","UK3CB_BAF_LLM_IR_Black","rhsusf_acc_su230a",["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",200],[],"rhsusf_acc_grip4_bipod"],[],[],["ARD_MC_Camo_Cyre_SS",[["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",2],["ACE_splint",1],["ACRE_PRC152",1],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2]]],["rhsusf_mbav_mg",[["ACE_CTS9",2,1],["B_IR_Grenade",1,1],["UK3CB_BAF_SmokeShell",4,1],["rhs_mag_m67",2,1],["rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",3,100]]],[],"rhsusf_opscore_mc_cover_pelt_cam","UK3CB_BAF_G_Tactical_Grey",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","JAS_GPNVG18_Tan"]]];
private _sasTp = ["[SAS] TP", [["UK3CB_BAF_L129A1","UK3CB_BAF_Silencer_L115A3","","rhsusf_acc_M8541_mrds",["UK3CB_BAF_762_L42A1_20Rnd",20],[],"UK3CB_underbarrel_acc_fgrip_bipod"],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["ARD_MC_Camo_Cyre_SS",[["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",2],["ACE_splint",1],["ACRE_PRC152",1],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_RangeCard",1],["ACE_Kestrel4500",1]]],["Crye_AVS_1",[["UK3CB_BAF_762_L42A1_20Rnd",7,20],["rhsusf_mag_17Rnd_9x19_FMJ",1,17]]],["rhsusf_falconii_mc",[["ACE_Tripod",1],["ACE_EntrenchingTool",1],["UK3CB_BAF_762_L42A1_20Rnd",2,20],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",1,1],["UK3CB_BAF_SmokeShellRed",1,1],["B_IR_Grenade",1,1],["HandGrenade",2,1],["ACE_CTS9",2,1],["ACE_Chemlight_IR",2,1]]],"rhsusf_opscore_mc_cover_pelt_nsw","UK3CB_BAF_G_Tactical_Grey",["UK3CB_BAF_Soflam_Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","JAS_GPNVG18_Tan"]]];
private _sasGl = ["[SAS] Grenadier", [["rhs_weap_m4a1_m320","rhsusf_acc_rotex5_grey","UK3CB_BAF_LLM_IR_Black","rhsusf_acc_g33_T1",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],["rhs_mag_M433_HEDP",1],""],[],["UK3CB_BAF_L105A2","","UK3CB_BAF_Flashlight_L105A1","",["UK3CB_BAF_9_15Rnd",15],[],""],["ARD_MC_Camo_Cyre_SS",[["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",2],["ACE_splint",1],["ACRE_PRC152",1],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2]]],["rhsusf_mbav_grenadier",[["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30],["UK3CB_BAF_9_15Rnd",2,15],["UK3CB_BAF_SmokeShell",2,1],["UK3CB_BAF_SmokeShellBlue",1,1],["ACE_CTS9",2,1],["HandGrenade",2,1]]],["rhsusf_falconii_coy",[["rhs_mag_M433_HEDP",14,1],["rhs_mag_m714_White",4,1],["rhs_mag_m713_Red",2,1],["ACE_40mm_Flare_ir",4,1]]],"rhsusf_opscore_mc_cover_pelt_cam","UK3CB_BAF_G_Tactical_Grey",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","JAS_GPNVG18_Tan"]]];
private _sasEod = ["[SAS] EOD", [["rhs_weap_m4a1_mstock","rhsusf_acc_nt4_black","rhsusf_acc_anpeq15","rhsusf_acc_g33_xps3",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip3"],[],["ACE_VMM3","","","",[],[],""],["ARD_MC_Tan_Camo_Cyre_SS",[["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",2],["ACE_splint",1],["ACRE_PRC152",1],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2]]],["Crye_AVS_1_2_Tan",[["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30],["UK3CB_BAF_SmokeShellBlue",1,1],["UK3CB_BAF_SmokeShellRed",1,1],["UK3CB_BAF_SmokeShell",4,1],["HandGrenade",2,1],["ACE_CTS9",2,1],["ACE_Chemlight_IR",2,1]]],["UK3CB_BAF_B_Bergen_MTP_Engineer_L_A",[["ACE_Clacker",1],["ACE_DefusalKit",1],["ACE_EntrenchingTool",1],["ACE_wirecutter",1],["ACE_SpraypaintRed",1],["ACE_SpraypaintBlue",1],["rhsusf_m112_mag",2,1],["SatchelCharge_Remote_Mag",1,1]]],"rhsusf_opscore_mc_cover_pelt_cam","UK3CB_BAF_G_Tactical_Grey",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","JAS_GPNVG18_Tan"]]];
private _sasMedic = ["[SAS] Médecin", [["rhs_weap_m4a1_mstock","rhsusf_acc_nt4_black","rhsusf_acc_anpeq15_light","rhsusf_acc_g33_T1",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_grip3"],[],[],["ARD_MC_OD_Camo_Cyre_SS",[["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",2],["ACE_splint",1],["ACRE_PRC152",1],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2]]],["rhsusf_mbav_medic",[["B_IR_Grenade",1,1],["UK3CB_BAF_SmokeShell",6,1],["UK3CB_BAF_SmokeShellBlue",2,1],["rhs_mag_m67",2,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",8,30]]],["B_Kitbag_cbr",[["ACE_packingBandage",12],["ACE_elasticBandage",12],["ACE_morphine",11],["ACE_epinephrine",10],["ACE_splint",6],["ACE_quikclot",10],["ACE_salineIV",10],["ACE_salineIV_250",8],["ACE_salineIV_500",10],["ACE_surgicalKit",1]]],"rhsusf_opscore_mc_cover_pelt_nsw","UK3CB_BAF_G_Tactical_Grey",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","JAS_GPNVG18_Tan"]]];
private _sasFac = ["[SAS] FAC", [["rhs_weap_m4a1_mstock","rhsusf_acc_nt4_tan","rhsusf_acc_anpeq15","rhsusf_acc_g33_xps3",["rhs_mag_30Rnd_556x45_M855_PMAG_Tan_Tracer_Red",30],[],"rhsusf_acc_grip3"],[],["rhsusf_weap_glock17g4","","","",["UK3CB_BAF_9_17Rnd",17],[],""],["ARD_MC_OD_Camo_Cyre_SS",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",4],["ACE_epinephrine",2],["ACE_splint",1],["ACE_tourniquet",2],["ACE_Flashlight_MX991",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2]]],["Crye_AVS_3_2",[["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan",6,30],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",1,1],["UK3CB_BAF_SmokeShellRed",1,1],["B_IR_Grenade",1,1],["HandGrenade",1,1],["ACE_CTS9",2,1]]],["UK3CB_BAF_B_Bergen_MTP_JTAC_L_A",[["ACRE_PRC117F",1],["ACRE_PRC152",1]]],"rhsusf_opscore_mc_cover_pelt_cam","UK3CB_BAF_G_Tactical_Grey",["UK3CB_BAF_Soflam_Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","B_UavTerminal","","ItemCompass","ACE_Altimeter","JAS_GPNVG18_Tan"]]];

private _sasSniper = ["[SAS] Sniper", [["rhs_weap_XM2010_wd","rhsusf_acc_M2010S_wd","UK3CB_BAF_LLM_IR_Black","rhsusf_acc_M8541_wd",["rhsusf_5Rnd_300winmag_xm2010",5],[],"rhsusf_acc_harris_bipod"],[],["rhsusf_weap_MP7A2_folded","rhsusf_acc_rotex_mp7","UK3CB_BAF_LLM_IR_Black","rhsusf_acc_eotech_xps3",["rhsusf_mag_40Rnd_46x30_FMJ",40],[],""],["ARD_MC_Ghillie_Camo_Cyre",[["ACE_EarPlugs",1],["ACE_elasticBandage",4],["ACE_packingBandage",4],["ACE_IR_Strobe_Item",2],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_splint",1],["ACRE_PRC152",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1]]],["rhsusf_mbav_mg",[["rhsusf_mag_40Rnd_46x30_AP",5,40],["rhsusf_5Rnd_300winmag_xm2010",10,5],["UK3CB_BAF_SmokeShellBlue",2,1],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellRed",1,1],["B_IR_Grenade",2,1],["HandGrenade",2,1],["ACE_Chemlight_IR",2,1]]],["B_AssaultPack_cbr",[["ACE_ATragMX",1],["ACE_Tripod",1],["ACE_EntrenchingTool",1],["ACE_RangeCard",1],["ACE_Kestrel4500",1],["ACE_Flashlight_MX991",1],["rhsusf_acc_premier_anpvs27",1]]],"rhsusf_opscore_rg_cover","",["rhsusf_bino_lrf_Vector21","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","JAS_GPNVG18_blk"]]];
private _sasSpotter = ["[SAS] Spotteur", [["UK3CB_BAF_L129A1","UK3CB_BAF_Silencer_L115A3","","rhsusf_acc_premier_mrds",["UK3CB_BAF_762_L42A1_20Rnd",20],[],"UK3CB_underbarrel_acc_fgrip_bipod"],[],["rhsusf_weap_MP7A2_folded","rhsusf_acc_rotex_mp7","UK3CB_BAF_LLM_IR_Black","rhsusf_acc_eotech_xps3",["rhsusf_mag_40Rnd_46x30_FMJ",40],[],""],["ARD_MC_Ghillie_Camo_Cyre",[["ACE_splint",1],["ACE_epinephrine",2],["ACE_morphine",4],["ACE_IR_Strobe_Item",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_Flashlight_MX991",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACRE_PRC152",1]]],["rhsusf_mbav_mg",[["UK3CB_BAF_762_L42A1_20Rnd",7,20],["rhsusf_mag_40Rnd_46x30_AP",4,40]]],["B_AssaultPack_rgr",[["ACE_Tripod",1],["ACE_EntrenchingTool",1],["ACE_RangeCard",1],["ACE_ATragMX",1],["UK3CB_BAF_MaxiKite",1],["ACE_Chemlight_IR",2,1],["UK3CB_BAF_SmokeShellBlue",2,1],["UK3CB_BAF_SmokeShell",4,1],["rhs_mag_m67",2,1],["B_IR_Grenade",2,1]]],"rhsusf_opscore_fg","",["UK3CB_BAF_Soflam_Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","JAS_GPNVG18_blk"]]];

// Royal Tanks
private _tankCrewman = ["[Royal Tank] Crewman", [["UK3CB_BAF_L22A2","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_EOT552",["UK3CB_BAF_556_30Rnd",30],[],""],[],[],["UK3CB_BAF_U_Smock_MTP",[["ACE_splint",1],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_IR_Strobe_Item",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_Flashlight_MX991",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",2],["ACRE_PRC343",1]]],["UK3CB_BAF_V_Osprey_Rifleman_A",[["UK3CB_BAF_556_30Rnd",6,30],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",2,1],["B_IR_Grenade",1,1],["HandGrenade",2,1],["ACE_Chemlight_IR",2,1]]],["UK3CB_BAF_B_Bergen_MTP_Rifleman_L_B",[["ToolKit",1]]],"UK3CB_BAF_H_CrewHelmet_ESS_A","UK3CB_BAF_G_Tactical_Grey",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]];

// RAF
// Helo
private _rafHeloPilot = ["[Royal Air Force] Pilote hélico", [["UK3CB_BAF_L22A2","UK3CB_BAF_SFFH","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_EOT552",["UK3CB_BAF_556_30Rnd",30],[],""],[],["UK3CB_BAF_L131A1","","","",["UK3CB_BAF_9_17Rnd",17],[],""],["UK3CB_BAF_U_HeliPilotCoveralls_RAF",[["ACE_splint",1],["ACE_epinephrine",2],["ACE_morphine",4],["ACE_IR_Strobe_Item",2],["ACE_packingBandage",4],["ACE_elasticBandage",4],["ACE_EarPlugs",1],["ACE_Flashlight_MX991",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACRE_PRC152",1]]],["FIR_pilot_vest",[["UK3CB_BAF_556_30Rnd",6,30],["UK3CB_BAF_SmokeShell",4,1],["UK3CB_BAF_SmokeShellBlue",1,1],["B_IR_Grenade",1,1],["HandGrenade",2,1],["ACE_Chemlight_IR",2,1],["UK3CB_BAF_9_17Rnd",1,17]]],["B_AssaultPack_rgr",[["ToolKit",1]]],"rhsusf_hgu56p_visor_green","",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter",""]]];

// Planes
private _rafF35Pilot = ["[Royal Air Force] Pilote F-35", [[],[],["UK3CB_BAF_L131A1","","","",["UK3CB_BAF_9_17Rnd",17],[],""],["U_I_pilotCoveralls",[["ACE_epinephrine",2],["ACE_morphine",2],["ACE_splint",1],["ACE_IR_Strobe_Item",2],["ACE_packingBandage",2],["ACE_elasticBandage",2],["ACE_EarPlugs",1],["ACE_Flashlight_MX991",1],["ACE_tourniquet",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_CableTie",1],["ACRE_PRC152",1],["UK3CB_BAF_SmokeShell",2,1],["B_IR_Grenade",1,1],["ACE_Chemlight_IR",2,1],["UK3CB_BAF_SmokeShellBlue",1,1],["UK3CB_BAF_9_17Rnd",1,17]]],[],["B_AssaultPack_cbr",[["ToolKit",1]]],"FIR_JHMCS","",[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]];

{
	_x params ["_name", "_loadout"];
	[_name, _loadout] call ace_arsenal_fnc_addDefaultLoadout;
} forEach [
	_brief,
	_briefTank,
	_briefingRaf,
	_birefingSas,
	_infCds,
	_infJtac,
	_infMedic,
	_infGenieEOD,
	_infRifleman,
	_infGl,
	_infHeavyMg,
	_infMg,
	_infMarksman,
	_infHeavyAt,
	_infMortar,
	_infMortarAssist,
	_infNrbcOperator,
	_sasLead,
	_sasOperator,
	_sasMg,
	_sasTp,
	_sasGl,
	_sasEod,
	_sasMedic,
	_sasFac,
	_sasSniper,
	_sasSpotter,
	_tankCrewman,
	_rafHeloPilot,
	_rafF35Pilot
];